SW468413: Platform event message command support not needed on WS
ibm-openbmc/phosphor-host-ipmid pull request #2
Opened 2019-09-20 13:01 UTC by tomjoseph83

Add compilation flag so that this command can be turned off on
OpenPower systems.

https://github.com/openbmc/phosphor-host-ipmid/issues/141

Change-Id: I42138e6043c32c1e7f8704e7864af301f3c6cd67
Signed-off-by: Tom Joseph <tomjoseph@in.ibm.com>

2019-09-21 17:21 UTC, dkodihal requested changes
Don't see a compiler flag, as the commit message states. Does IPMI have a way to turn command support on/off per platform?

2019-09-22 14:14 UTC, tomjoseph83 commented
@dkodihal The compiler flag needs to be added, created the issue to track that. The commit message was misleading corrected it.

2019-09-22 15:08 UTC, dkodihal commented
@tomjoseph83 Why not add the compile flag upstream and use that solution?

2019-09-22 15:24 UTC, tomjoseph83 commented
@dkodihal Adding the compile flag upstream will be done once the OP940 defects are tackled. I have tried to keep this fix very minimal.

2019-09-22 16:28 UTC, dkodihal approved these changes

2019-09-23 17:42 UTC, merged